language: java

jdk: oraclejdk8

env:
  - MAVEN_VERSION=3.3.9

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode clean install"

cache:
  directories:
  - $HOME/.m2

before_install:
  - "docker-compose up -d"

services:
  - docker

after_success:
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL