language: java

jdk: oraclejdk8

env:
  - MAVEN_VERSION=3.3.9
  - WEBHOOK_URL=https://discordapp.com/api/webhooks/562261833143025664/1lYVssTL5bXdSvf9BS9UlGb3_FPdeHKJKeOA42zhXIJ7gZ2jWVG4ilSNg6tT9cv2N9R_

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode clean install"

cache:
  directories:
  - $HOME/.m2

before_install:
  - "docker-compose up -d"

services:
  - docker

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL