language: java

jdk: oraclejdk8

git:
  depth: 3

branches:
  only:
    - master

env:
  - MAVEN_VERSION=3.3.9

before_install:
  - chmod +x ./ecr_credentials.sh
  - ./ecr_credentials.sh

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"

script: "./mvnw --show-version --errors --batch-mode clean install"

cache:
  directories:
  - $HOME/.m2

after_success:
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL