language: java

jdk: oraclejdk8

before_deploy:
  - chmod +x ./ecr_credentials.sh
  - ./ecr_credentials.sh

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "eu-west-3"
  app: "lightnin-school"
  env: "LightninSchool-env"
  bucket_name: "eb-lightning-school"

env:
  - MAVEN_VERSION=3.3.9

before_install:
  - chmod +x ./ecr_credentials.sh
  - ./ecr_credentials.sh

install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"

script: "./mvnw --show-version --errors --batch-mode clean install"

cache:
  directories:
  - $HOME/.m2

after_success:
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL