version: '3.1'

services:

  mysql:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lightning_school
    ports:
      - 3306:3306

  neo4j:
    image: neo4j:3.5
    restart: always
    environment:
      NEO4J_dbms_memory_pagecache_size: 1G
    volumes:
      - ./db/neo4j/data:/data
      - ./db/neo4j/logs:/logs
    ports:
      - 7474:7474
      - 7687:7687